from enum import Enum


class SetType(str, Enum):
    WARM_UP = "WARM_UP"
    NORMAL = "NORMAL"
    DROP_SET = "DROP_SET"
    FAILURE = "FAILURE"


class MuscleGroup(str, Enum):
    CHEST = "CHEST"
    LATS = "LATS"
    UPPER_BACK = "UPPER_BACK"
    TRAPS = "TRAPS"

    BICEPS = "BICEPS"
    TRICEPS = "TRICEPS"
    FOREARMS = "FOREARMS"

    FRONT_DELTS = "FRONT_DELTS"
    SIDE_DELTS = "SIDE_DELTS"
    REAR_DELTS = "REAR_DELTS"

    QUADS = "QUADS"
    HAMSTRINGS = "HAMSTRINGS"
    GLUTES = "GLUTES"

    CALVES = "CALVES"

    ABS = "ABS"
    OBLIQUES = "OBLIQUES"

    LOWER_BACK = "LOWER_BACK"

    ADDUCTORS = "ADDUCTORS"
    ABDUCTORS = "ABDUCTORS"

    CARDIO = "CARDIO"


class Equipment(str, Enum):
    NONE = "NONE"
    BARBELL = "BARBELL"
    DUMBBELL = "DUMBBELL"
    KETTLEBELL = "KETTLEBELL"
    CABLE = "CABLE"
    MACHINE = "MACHINE"
    PLATE = "PLATE"
