"""add completed to sets

Revision ID: 2e2a4014aaa9
Revises: 0bed9083bb12
Create Date: 2026-09-10 22:37:53.804842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e2a4014aaa9"
down_revision: Union[str, Sequence[str], None] = "0bed9083bb12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sets",
        sa.Column("completed", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sets", "completed")
    # ### end Alembic commands ###
