"""add title and image_url to workout_posts

Revision ID: 64043cb45a56
Revises: 2e2a4014aaa9
Create Date: 2026-09-10 23:28:09.751413

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64043cb45a56"
down_revision: Union[str, Sequence[str], None] = "2e2a4014aaa9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workout_posts", sa.Column("title", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "workout_posts", sa.Column("image_url", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workout_posts", "image_url")
    op.drop_column("workout_posts", "title")
    # ### end Alembic commands ###
