"""convert exercise primary_muscle and equipment to enums

Revision ID: 6c80da04b1ba
Revises: 8c7f0b8e4b2a
Create Date: 2026-07-02 13:37:10.611580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c80da04b1ba'
down_revision: Union[str, Sequence[str], None] = '8c7f0b8e4b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    musclegroup_enum = sa.Enum(
        'CHEST', 'LATS', 'UPPER_BACK', 'TRAPS', 'BICEPS', 'TRICEPS', 'FOREARMS',
        'FRONT_DELTS', 'SIDE_DELTS', 'REAR_DELTS', 'QUADS', 'HAMSTRINGS', 'GLUTES',
        'CALVES', 'ABS', 'OBLIQUES', 'LOWER_BACK', 'ADDUCTORS', 'ABDUCTORS',
        'CARDIO', name='musclegroup'
    )
    equipment_enum = sa.Enum(
        'NONE', 'BARBELL', 'DUMBBELL', 'KETTLEBELL', 'CABLE', 'MACHINE', 'PLATE',
        name='equipment'
    )
    musclegroup_enum.create(op.get_bind(), checkfirst=True)
    equipment_enum.create(op.get_bind(), checkfirst=True)

    op.execute("UPDATE exercises SET primary_muscle = upper(primary_muscle)")
    op.execute("UPDATE exercises SET equipment = upper(equipment)")
    op.execute(
        """
        UPDATE exercises
        SET secondary_muscles = ARRAY(
            SELECT upper(muscle)
            FROM unnest(secondary_muscles) AS muscle
        )
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'primary_muscle',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CHEST', 'LATS', 'UPPER_BACK', 'TRAPS', 'BICEPS', 'TRICEPS', 'FOREARMS', 'FRONT_DELTS', 'SIDE_DELTS', 'REAR_DELTS', 'QUADS', 'HAMSTRINGS', 'GLUTES', 'CALVES', 'ABS', 'OBLIQUES', 'LOWER_BACK', 'ADDUCTORS', 'ABDUCTORS', 'CARDIO', name='musclegroup'),
               existing_nullable=False,
               postgresql_using='primary_muscle::musclegroup')
    op.alter_column('exercises', 'secondary_muscles',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               type_=sa.ARRAY(sa.Enum('CHEST', 'LATS', 'UPPER_BACK', 'TRAPS', 'BICEPS', 'TRICEPS', 'FOREARMS', 'FRONT_DELTS', 'SIDE_DELTS', 'REAR_DELTS', 'QUADS', 'HAMSTRINGS', 'GLUTES', 'CALVES', 'ABS', 'OBLIQUES', 'LOWER_BACK', 'ADDUCTORS', 'ABDUCTORS', 'CARDIO', name='musclegroup')),
               existing_nullable=False,
               postgresql_using='secondary_muscles::musclegroup[]')
    op.alter_column('exercises', 'equipment',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('NONE', 'BARBELL', 'DUMBBELL', 'KETTLEBELL', 'CABLE', 'MACHINE', 'PLATE', name='equipment'),
               existing_nullable=False,
               postgresql_using='equipment::equipment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'equipment',
               existing_type=sa.Enum('NONE', 'BARBELL', 'DUMBBELL', 'KETTLEBELL', 'CABLE', 'MACHINE', 'PLATE', name='equipment'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='equipment::text')
    op.alter_column('exercises', 'secondary_muscles',
               existing_type=sa.ARRAY(sa.Enum('CHEST', 'LATS', 'UPPER_BACK', 'TRAPS', 'BICEPS', 'TRICEPS', 'FOREARMS', 'FRONT_DELTS', 'SIDE_DELTS', 'REAR_DELTS', 'QUADS', 'HAMSTRINGS', 'GLUTES', 'CALVES', 'ABS', 'OBLIQUES', 'LOWER_BACK', 'ADDUCTORS', 'ABDUCTORS', 'CARDIO', name='musclegroup')),
               type_=postgresql.ARRAY(sa.VARCHAR(length=50)),
               existing_nullable=False,
               postgresql_using='secondary_muscles::text[]')
    op.alter_column('exercises', 'primary_muscle',
               existing_type=sa.Enum('CHEST', 'LATS', 'UPPER_BACK', 'TRAPS', 'BICEPS', 'TRICEPS', 'FOREARMS', 'FRONT_DELTS', 'SIDE_DELTS', 'REAR_DELTS', 'QUADS', 'HAMSTRINGS', 'GLUTES', 'CALVES', 'ABS', 'OBLIQUES', 'LOWER_BACK', 'ADDUCTORS', 'ABDUCTORS', 'CARDIO', name='musclegroup'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='primary_muscle::text')
    # ### end Alembic commands ###
    sa.Enum(name='musclegroup').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='equipment').drop(op.get_bind(), checkfirst=True)
