"""add timezone awareness to user timestamps

Revision ID: 948d760e7f34
Revises: 6c80da04b1ba
Create Date: 2026-07-06 00:36:02.397292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '948d760e7f34'
down_revision: Union[str, Sequence[str], None] = '6c80da04b1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sets', 'rpe',
               existing_type=sa.NUMERIC(precision=2, scale=1),
               type_=sa.Numeric(precision=3, scale=1),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sets', 'rpe',
               existing_type=sa.Numeric(precision=3, scale=1),
               type_=sa.NUMERIC(precision=2, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###
